from config import all_line, program_authentication_clyth
years_copyleft = "2024 - 2026"

#Локализации
localizations = {
    "ct": {
        "": "",
    },
    "ru": {
        "RLP": "Защита Нагрузки",
        "ARM": "Мастер Автозагрузки",
        "AX": "АнтиХерня",
        "PM": "Менеджер Процессов",
        "FM": "Файловый Менеджер",
        "UA": "Разблокировка всего",
        "FE": "Редактор Файлов",
        "FR": "Замена редко используемых файлов",
        "CM": "Главное меню",
        "SP": "Пугало от вирусов",
        "CC": "Очистка Кэша",
        "Console": "Консоль разработчика",
        "UM": "Менеджер Пользователей",
        "R": "Перезапуск ПК",
        "Run": "Запуск от имени администратора",
        "OBPC": "Голосовое Управление",
        "CC22": 'Шифрование "Шифр Цезаря"',
        "EC": "Изменение Критичности процесса",
        "GFA": "Получение полных прав",
        "OF": "Прочие Компоненты",
        "RS": "Генератор Заголовков",
        "E": "Выход из программы",
        "AP": "О Программе",
        "SAU": "Настройки",
        #AP
        "version_component": "Версии Компонентов",
        "pac": "Ключ КПП",
        "general_component": "Главные Компоненты",
        "program_kernel": "Ядро программы (трей)",
        "mini_component": "Мини Компоненты",
        "system_component": "Системные Компоненты",
        "support_text": "Поддержать нас можно, перейдя по ссылке и оплатив 2 банки сгущёнки:",
        "steam_trade_text": "или поддержать через Обмен в Steam",
        "donation_alerts_text": "Поддержать нас через DonationAlerts или Steam",
        "license": "Лицензия",
        "website_neo_organization": "Веб-Сайт NEO Organization",
        "about_program_text": f"Антивирус Монтировка!\nВытащит любой гвоздь из крышки гроба вашего ПК!\n(как минимум попытается, а если не смог - поставь Linux)\nCreated by NEO Organization\nPowered by Departament K\nCoded by @AnonimNEO, Всего строчек кода : {all_line}\nПрограммисты/Задумщики/Художники/Тестировщики : @AnonimNEO\nЛицензия: GPL v3.0 Copyleft 🄯 {years_copyleft}\n",
        "ap_exception_text": "В Компоненте AboutProgram произошла неизвестная ошибка!",
        "not_stable": "не доступен из-за нестабильности",
        "read_dir_error": "Ошибка при чтении каталога",
        "read_image_error": "Не удалось загрузить изображение",
        #T
        "import_error": "Ошибка импорта",
        "replacement_is_used": "Используется замена",
        "component_import_error": "Ошибка импорта Компонента",
        "component": "Компонент",
        "not_available": "не доступен",
        "not_available2": "не доступна",
        "library": "Библиотека",
        "critical_fail_detect": "Обнаружены критические повреждения программы! Ядро программы не может быть запущено",
        "damage": "Повреждения",
        "run_in_recovery": "Запуск в среде восстановления Шindows",
        "run_in_normal": "Запуск в стандартной среде Шindows",
        "environment_error": "Ошибка при определении среды",
        "load_bush": "Загрузка кустов реестра с диска",
        "unload_bush": "Завершение работы, выгрузка кустов реестра...",
        "runtime_error": "Критическая ошибка при инициализации программы",
        "use_default_font": "Используется шрифт по умолчанию",
        "trey_error": "Ошибка трея",
        "open_with": "Открыть с помощью",
        "bad_password_for_console": "Неправильный ввод капчи.\nКонсоль разработчика не будет запущена.",
        "enter_number": "Введите число",
        "open": "Открыть",
        "utilities": "Утилиты",
        "icon_start_error": "Ошибка запуска иконки",
        "t_critical_error": "В Компоненте Trey произошла неизвестная ошибка",
        "multiprocessing_error": "Критическая ошибка при многопоточности",
        "restart_program": "Перезапустить программу",
        "admin_error": "Ошибка при получении прав администратора",
        #ARM
        "scheduler_error": "Не удалось подключиться к планировщику задач",
        "edit_task_error": "Ошибка изменения состояния задачи",
        "delete_task_error": "Ошибка удаления задачи",
        "user_not_found": "Не найден пользователь",
        "enter_user_name": "Введите нужное имя пользователя",
        "metadata_error": "Ошибка при получении метаданных файла",
        "startup_error": "Ошибка при доступе к папке автозагрузки пользователя",
        "key_not_found": "Ключ реестра не найден",
        "read_key_error": "Ошибка при считывании ключа реестра",
        "create_key": "Создан параметр реестра",
        "with_type": "с типом",
        "in": "в",
        "permission_error": "Недостаточно прав",
        "create_key_error": "Ошибка при создании параметра реестра",
        "update_key": "Успешно изменён параметр реестра",
        "update_key_error": "Ошибка при изменении параметра реестра",
        "delete_key": "Удален параметр реестра",
        "delete_key_error": "Удален параметр реестра",
        "file_delete": "Удалён файл",
        "file_delete_error": "Ошибка при удалении файла",
        "save_xml_task_error": "Ошибка сохранения XML задачи",
        "task_error": "Ошибка обработки задачи",
        "task_dir_error": "Каталог задач не найден",
        "xml_task_error": "Ошибка обработки файла задачи",
        "on": "включена",
        "off": "отключена",
        "task": "Задача",
        "success": "успешно",
        "from_com": "через COM",
        "from_xml": "через XML",
        "xml_error": "Ошибка XML",
        "delete_task_com": "удалена через COM",
        "xml_task_delete": "XML файл задачи удален",
        "xml_task_delete_error": "Ошибка удаления XML файла",
        "delete_file?": "Вы уверены, что хотите удалить параметр реестра",
        "enter_new_name_key": "Введите имя нового параметра реестра",
        "for": "для",
        "arm_help_text": 'Во вкладке планировщик отображается так много задач, потому что вирусы могли модернизировать задачи, но такое крайне редко, поэтому вы можете отключить отображение задач без графа "создан". Для этого нажмите на пункт в верхней панели окна: вид->Показывать только задачи с датой.',
        "arm_critical_error": f"В Компоненте AutoRunMaster произошла неизвестная ошибка!",
        #Console
        "crowbar_console": "Консоль Разработчика Антивируса Монтировка",
        "crowbar_console_text": "Будьте осторожны, данный компонент может быть не стабилен\nА не понимание, что выделаете можете привести к повреждению программы\nЕсли это произошло перезапустите программу.\n",
        "attempt_command": "попытка выполнить команду",
        "exit_with_console_text": "Не не Я не дам тебе обойти капчу (как минимум попытаюсь)",
        #EC
        "open_process_error": "Не удалось открыть процесс",
        "error_code": "Код ошибки",
        "installed": "установлена",
        "removed": "снята",
        "process_critical": "Критичность процесса",
        "target": "целевое",
        "edit_critical_error": "Ошибка при изменения критичности",
        "edit_critical_unknown_error": "Неизвестная ошибка при изменении критичности",
        "process": "Процесс",
        "not_found": "не найден",
        "criticality_status": "Значение критичности процесса",
        "changed_to": "изменено на",
        "no_changed": "не было изменено",
        "ec_critical_error": "В Компоненте EditCriticality произошла неизвестная ошибка",
        #OF
        "pac_text": f"Ключ Подлинности Программы (КПП) - это ключ для подтверждения, что эта программа подлинная.\nЕсли вы видите ключ который вы указывали при компиляции, значит перед вами настоящий Антивирус Монтировка.\nЕсли ключ не совпадает с вашим - значит перед вами клон программы который маскируется под Антивирус Монтировка.\n\nКПП - {program_authentication_clyth}",
        "start_thread": "Успешно запущен поток для",
        "start_process": "Успешно запущен процесс для",
        "start_theard_error": "Ошибка при запуске потока для процесса",
        "start_process_error": "Ошибка при запуске процесса для процесса",
        "restart_ca": "Перезапуск программы",
        "system_found": "Система найдена на",
        "unknown_error": "Неизвестная ошибка",
        "bush_not_found": "Файл куста не найден",
        "bush": "Куст",
        "success_load": "успешно загружен из",
        "load_bush_error": "Ошибка при загрузке куста",
        "success_unload": "успешно выгружен",
        "unload_bush_error": "Ошибка при выгрузке куста",
        "get_user_name_error": "Ошибка получения имени пользователя",
        "open_file_error": "Не удалось открыть файл",
        "with_program": "с помощью указанной программы",
        "start_error": "Ошибка при запуске",
        "start_command_error": "Ошибка при выполнении команды",
        #E
        "dyrachok_test_log_text": "Проверка на дурочка не прошла",
        "dyrachok_test_text": "Вы смотрите тикток!\nПрограмма не будет закрыта.",
        "watch_tiktok?": "Смотрите ли вы тикток?",
        "exit_error": "Ошибка при выходе",
        "exit_program": "Завершение работы программы...",
        "bad_capcha": "Неправильный ввод капчи.\nПрограмма не будет закрыта.",
        "enter_result_example": "Введите результат данного примера",
        "bad_result_example": "ввод примера не верен",
        "bad_enter_number": "Неправильный ввод числа",
        "want_exit?": "Вы действительно хотите выйти из данного программного обеспечения?",
        "attempting_to_exit": "Попытка выхода из программы",
        "cancel_exit": "Отмена выхода",
        "e_critical_error": "В Компоненте Exit произошла неизвестная ошибка!",
        #GFA
        "not_dir": "Путь не существует",
        "full_access_set": "Полные права установлены",
        "error": "Ошибка",
        "file_error": "Ошибка при работе с файлом",
        "to_access": "для доступа к",
        "get_sid_error": "Ошибка получения SID пользователя",
        "get_description_error": "Ошибка получения дескриптора безопасности",
        "ace_error": "Ошибка добавления ACE",
        "set_access_error": "Ошибка установки прав",
        "success_set_full_access": "Полные права на реестр установлены",
        "regedit_error": "Ошибка при работе с реестром",
        #R
        "attempt_to_reboot": "Попытка перезагрузки через",
        "r_critical_error": "В Компоненте Restart произошла неизвестная ошибка в методе",
        "next_method": "Переход к следующему способу",
        "all_method_used": "Были выполнены все возможные способы перезагрузки шindows, не один не увенчался успехом.",
        #SP
        "simulation": "Симуляция",
        "removal": "Удаление",
        "create_dir": "Создан каталог",
        "create_dir_error": "Ошибка при создании каталога",
        "create_file": "Создан файл",
        "create_file_error": "Ошибка при создании файла",
        "delete_dir": "Удалён каталог",
        "delete_dir_error": "Ошибка при удалении каталога",
        "start_simulation": "Запуск симуляции для",
        "simulation_for": "Симуляция для",
        "completed": "завершена",
        "simulation_completed": "Симуляция завершена.",
        "sp_confirmation": "Вы уверены, что хотите удалить все фантомные элементы?\nЭто может повредить настоящие установленные.",
        "delete_simulation": "Удаление симуляции для",
        "delete_simulation_for": "Удаление симуляции для",
        "delete_completed": "Удаление завершено.",
        "sp_critical_error": f"В Компоненте ScarecrowProtection произошла неизвестная ошибка!",
        #UA
        "start_recovery_font": "Начало восстановления шрифтов",
        "font_dir_not_found": "Каталог шрифтов не найден",
        "font": "Шрифт",
        "restored": "восстановлен",
        "correct_font": "уже корректно записан в реестре",
        "add_in_registry": "добавлен в реестр",
        "font_error": "Ошибка при обработке шрифта",
        "delete_orphan_font": "Удалён параметр сиротского шрифта",
        "delete_orphan_font_error": "Ошибка при удалении параметра-сирот",
        "recovery_font_complete": "Восстановление шрифтов завершено. Найдено",
        "removed_orphans": "удалено сирот",
        "recovery_font_error": "Ошибка при восстановлении шрифтов",
        "parameter": "Параметр",
        "successfully_reset_to": "успешно сброшен в",
        "unsupported_type_for": "Неподдерживаемый тип для",
        "not_found_pass": "не найден, пропуск",
        "reset_error": "Ошибка при сбросе",
        "block_detect": "Обнаружены блокировки в",
        "delete_block": "Удалены блокировки",
        "component_work_complete": "Работа компонента завершена",
        "ua_critical_error": "В Компоненте UnlockAll произошла неизвестная ошибка:",
        "au_result": "Компонент разблокировка всего завершил работу результаты",
        "unlock": "Разблокировано✅",
        "unlock_error": "Ошибка разблокировки❌",
        "blocks": "Блокировки",
        "mouse": "мыши",
        "explorer": "проводника",
        "user": "пользователя",
        "systems": "системы",
        "fonts": "шрифтов",
        "check_fonts": "Проверка целостности шрифтов",
        "all_fonts=": "Все параметры шрифтов имеют одинаковое значение",
        "not_ttf_or_otf": "В значениях параметров отсутствуют .ttf или .otf файлы",
        "font_problem_detect": "Обнаружены проблемы с шрифтами, запуск восстановления",
        "restore_fonts_check_success": "Проверка целостности шрифтов завершена успешно, восстановление не требуется",
        "check_fonts_error": "Неизвестная ошибка при проверке шрифтов",
        #UM
        "net_error": "Команда net завершилась с ошибкой",
        "system_command_error": "Системная ошибка при выполнении команды",
        "user_name": "Имя пользователя",
        "create_user": "Создать пользователя",
        "delete_users": "Удалить выбранных",
        "change_password": "Изменить пароль",
        "get_user_list_error": "Ошибка при загрузке списка пользователей",
        "password": "Пароль",
        "enter_all_data": "Заполните все поля.",
        "success_create": "успешно создан",
        "create_user_error": "Ошибка при создании пользователя",
        "select_user": "Выберите пользователя.",
        "cant_delete_self": "Нельзя удалить себя",
        "what_did_you": "Иш, что захотел",
        "deleted": "удален",
        "delete_user_error": "Ошибка при удалении пользователя",
        "enter_new_password": "Введите новый пароль:",
        "not_empty": "не может быть пустым.",
        "reset": "Сбросить",
        "reset2": "сброшен",
        "password_for_user": "Пароль для пользователя",
        "change_password_error": "Ошибка при сбросе пароля для",
        "um_critical_error": "В Компоненте UsersManager произошла неизвестная ошибка!",
        #CC
        "start_clean": "Запуск Очистки",
        "from": "из",
        "delete_files_error": "Ошибка при удалении следующих файлов",
        "delete_files_success": "Успешно удалённые файлы",
        "cc_log_dir": "Лог файл был создан по пути",
        "cc_critical_error": "В Компоненте ClearCache произошла неизвестная ошибка!",
        #CM
        "components": "Компоненты",
        "protect": "Защита",
        "control": "Управление",
        "cm_critical_error": "В Компоненте CrowbarMenu произошла неизвестная ошибка!",
        #Theme
        "dark": "Тёмная",
        "white": "Светлая",
        "red": "Красная",
        "blue": "Синяя",
        "green": "Зелёная",
        "contrast": "Контрастная",
        "gray": "Серая",
        "orange": "Оранжевая",
        "themes": "Темы",
        "topmost": "Поверх всех окон",
        "on2": "вкл",
        "off2": "выкл",
        "help": "Помощь",
        "view": "Вид",
        "show_date": "Показывать только задачи с датой",
        #FE
        "file": "Файл",
        "save": "Сохранить",
        "save_as": "Сохранить как",
        "exit": "Выход",
        "editing": "Редактирование",
        "cancel": "Отменить",
        "repeat": "Повторить",
        "cut": "Вырезать",
        "copy": "Копировать",
        "paste": "Вставить",
        "select_all": "Выделить всё",
        "font_size": "Размер шрифта",
        "new_file": "Новый файл",
        "text_file": "Текстовые файлы",
        "all_files": "Все файлы",
        "file_not_found": "Файл не найден",
        "success_saved": "успешно сохранён",
        "save_changes?": "У вас есть несохранённые изменения. Сохранить файл перед выходом?",
        "match_case": "Учитывать регистр",
        "whole_words": "Слова Целиком",
        "back": "Назад",
        "next": "Далее",
        "fe_critical_error": "В Компоненте FileEditor произошла неизвестная ошибка!",
        "cuttlefish": "Сепия",
        #FR
        "created": "Создан",
        "replaced": "заменено",
        "on_disc": "на диске",
        "replace_file_not_found": "Не удалось заменить файл",
        "select_file": "Сначала выберите или укажите путь к файлу!",
        "backup": "Бэкап",
        "on_dir": "по пути",
        "restore": "Восстановить",
        "from_backup": "из бэкапа",
        "restore_from_backup": "Восстановлено из бэкапа",
        "when_restoring_a_file": "при восстановлении файла",
        "your_way": "Свой путь",
        "sticky_keys": "Залипание клавиш",
        "specialist_possibilities": "Спец. возможности",
        "task_manager": "Диспетчер задач",
        "explorer": "Проводник",
        "what_to_replace": "На, что заменить",
        "review": "Обзор",
        "what_are_replace": "Что заменяем",
        "select_preset": "Выберите пресет...",
        "replace": "Заменить",
        #FM
        "skip_file": "Пропущен файл",
        "copy_path": "Скопировать путь",
        "search": "Поиск",
        "loading": "Загрузка",
        "enter_path": "Введите путь",
        "available_disks": "Доступные диски",
        "path": "Путь",
        "delete": "Удалить",
        "elements": "элементов",
        "you_want_to_delete": "Вы уверены, что хотите удалить",
        "delete_error": "Ошибка при удалении",
        "elements_copy": "Скопировано элементов",
        "clipboard_is_empty": "Буфер обмена пуст",
        "paste_error": "Ошибка вставки",
        "access_check_error_for": "Ошибка проверки доступа для",
        "properties": "Свойства",
        "meaning": "Значение",
        "name": "Имя",
        "location": "Расположение",
        "size": "Размер",
        "changed": "Изменён",
        "opened": "Открыт",
        "file_version": "Версия файла",
        "author": "Автор",
        "access_for": "Права доступа (для",
        "full_access": "Полный доступ",
        "reading": "Чтение",
        "record": "Запись",
        "launch": "Запуск",
        "collecting_properties_error": "Ошибка при сборе свойств для",
        "read_file_properties_error": "Не удалось прочитать свойства файла",
        "invalid_characters": "содержит недопустимые символы",
        "current": "Текущий",
        "dir": "Каталог",
        "new_name_for": "Новое имя для",
        "already_exists": "уже существует",
        "name_file_or_dir": "Файл или каталог с именем",
        "renamed": "Переименовано",
        "when_renaming": "при переименовании",
        "enter_data_file": "Введите содержимое для файла",
        "restore_focus_error": "Не удалось восстановить фокус на",
        "up": "Вверх",
        "rename": "Переименовать",
        "get_full_access": "Получить полные права",
        "edit_file": "Отредактировать файл",
        "create": "Создать",
        "update": "Обновить",
        "not_dir_selected": "Не выбран каталог для вставки",
        "source_file_not_found": "Источник не найден (возможно, был перемещен)",
        "dont_copy_in_in": "Нельзя скопировать или переместить элемент в тот же каталог",
        "replace_it": "Заменить его?",
        "copied2": "Скопирован",
        "fm_help_text": "Добро пожаловать в Файловый Менеджер!\nДанный Компонент поддерживает:\n1)Полное управление с клавиатуры\n2)Поиск - чтобы его вызвать нажмите на пункт в верхней левой части окна.",
        "text_for_search": "Текст для поиска:",
        "in_current_dir": "В текущем каталоге",
        "cancel2": "Отмена",
        "enter_text_for_search": "Введите текст для поиска:",
        "not_current_tab_for_search": "Нет активной вкладки для поиска.",
        "files_containing": "Файлы, содержащие",
        "not_founded": "не найдены",
        "info_dir_error": "Ошибка получения информации о каталоге",
        "info_file_error": "Ошибка получения информации о файле",
        "search_result": "Результаты поиска",
        "fm_exit": "Вы уверены, что хотите выйти?",
        "fm_critical_error": "В FileManager произошла неизвестная ошибка!",
        #PM
        "info_process_error": "Ошибка при получении информации о процессе",
        "ok": "ОК",
        "at": "при",
        "kill_processes": "Убить процессы",
        "suspend": "Заморозить",
        "resume": "Разморозить",
        "make_it_critical": "Сделать критичными",
        "remove_criticality": "Снять критичность",
        "to_file": "к файлу",
        "pm_help_text": "Добро пожаловать в Менеджер Процессов, он поддерживает:\n1)Выделение нескольких процессов и работу с ними\n2)Поиск - чтобы его вызвать нажмите на пункт вверху левой части окна.\n3)Замороженные процессы - помечены серым цветом, а критические - красным. Также есть вкладки для удобной навигации.\n\nУчтите, что windows создаёт свои 4 критических процессов svhost.exe, но вирус может изменить эти значения, будьте бдительны!",
        "cancel_search": "Прекратить поиск",
        "actions": "Действия",
        "pm_critical_error": "В Компоненте ProcessManager произошла неизвестная ошибка!",
        "kill_delete_file_process": "Убить + удалить файл процесса",
        "process_dont_close": "не закрылся за 3 секунды",
        #Run
        "standard": "Стандартные",
        "regedit": "редактор реестра",
        "taskmgr": "диспетчер задач",
        "notepad": "блокнот",
        "explorer": "проводник",
        "cmd": "командная строка",
        "powershell": "PowerShell",
        "commands": "Команды",
        "cancel_reboot": "Отменить перезагрузку/выключение",
        "reboot_pc": "Перезагрузить ПК",
        "shutdown_pc": "Выключить ПК",
        "end_session": "завершить сеанс",
        "mode": "Режим:",
        "professional": "профессиональный",
        "simplified": "упрощённый",
        "file2": "файла",
        #SAU
        "compilations": "Компиляции",
        "command_end_with_code": "Команда завершилась с кодом",
        "t_compilation_is_finish": "Компиляция Компонента Trey завершена!",
        "setting_saved_in": "Настройки успешно сохранены в",
        "settings_save_error": "Ошибка при сохранении настроек",
        "settings_backup_created_ob_path": "Резервная копия настроек создана по пути",
        "settings_export_success": "Экспорт прошёл успешно, сохранено в",
        "settings_backup_created_error": "Ошибка при создании резервной копии",
        "settings_export_error": "Ошибка при экспорте настроек",
        "archive": "Архив",
        "not_compilation": "Перекомпиляция не возможна",
        "bad_archive": "Неверный формат архива или поврежденный архив",
        "success_unpacked": "успешно распакован",
        "unpacked_archive_error": "Ошибка при распаковке архива",
        "moved": "перемещено",
        "content": "Содержимое",
        "moved_error": "Ошибка при перемещении файлов",
        "enter_path_to_image": "Введите каталог куда переместить изображения\nНичего не вводите если изображения уже в нужном каталоге\n(например вы просто обновляете программу)",
        "for_copy_image": "изображений в каталог",
        "for_copy": "для копирования",
        "copy_error": "Ошибка при копировании",
        "copy_file_error": "изображений\nВозможно вы ввели неправильные данные, вы можете сами переместить файлы они находятся в каталоге с программой.",
        "enter_exe_name": "Введите каталог куда переместить исполняемый файл\nвместе с именем файла, обязательно с расширением .exe!",
        "copy_exe_error": "Возможно вы ввели неправильные данные, вы можете сами переместить файлы они находятся в каталоге с программой",
        "create_lnk_success": "Ярлык успешно создан на рабочем столе",
        "create_lnk_error": "Ошибки при создании ярлыка",
        "successfully_changed_to": "успешно изменено на",
        "add_to_autorun_error": "Ошибка при добавлении программы в автозагрузку",
        "add_program_to_autorun": "Добавить программу в автозагрузку?",
        "add_program_to_autorun_error": "Произошла ошибка во время добавления программы в автозагрузку",
        "path_must_string": "Путь должен быть строкой",
        "number_must_be_1_to": "Число должно быть от 1 до",
        "enter_number": "Введите число.",
        "enter_string": "Значение должно быть строкой",
        "field_cannot_be_empty": "Поле не может быть пустым.",
        "use": "Используйте",
        "must_list": "Должен быть список, кортеж, множество или словарь",
        "syntaxis_error": "Ошибка синтаксиса",
        "invalid_format": "Некорректный формат",
        "must_be_dictionary": "Значение должно быть словарем",
        "dictionary_must_contain_key": "Словарь должен содержать ключ",
        "read_comments_error": "Ошибка при чтении комментариев из",
        "parsing_error": "Ошибка парсинга",
        "fix_problem_in_fields": "Исправьте ошибки в полях (отмечены красным)",
        "recompilation_required_continue": "Требуется перекомпиляция!\nПродолжить?",
        "create_backup": "Создание резервной копии...",
        "create_backup_error": "Ошибка при создании бэкапа",
        "save_settings": "Сохранение настроек...",
        "save_settings_error": "Ошибка при сохранение настроек",
        "unpacking_source_code": "Распаковка исходников...",
        "unpacking_source_code_error": "Ошибка при распаковка исходников",
        "preparing_files": "Подготовка файлов...",
        "preparing_files": "Подготовка файлов...",
        "compilation": "Компиляция",
        "during_recompilation": "при перекомпиляции",
        "copying_files": "Копирование файлов...",
        "adding_to_autorun": "Добавление в автозагрузку...",
        "completed": "завершено",
        "delete_compiling_cache": "Вы уверены, что хотите удалить весь кэш и временные .py файлы?",
        "clean_completed_deleted_objects": "Очистка завершена.\nУдалено объектов",
        "clean_cache_error": "Ошибка при очистке кэша",
        "ready": "Готов к работе",
        "open_error": "Не удалось открыть",
        "log": "лог файла",
        "export": "Экспорт",
        "import": "Импорт",
        "delete_cache": "Удалить Кэш",
        "apply": "Применить",
        "sau_start_text": "Учтите, что изменение параметров невозможно без перекомпиляции программы!\n\nРекомендуем сделать экспорт настроек (тем самым сделать резервную копию настроек), перед изменениями\n\nВы хотите продолжить?",
        "icon_not_found": "Не найдена иконка программы, если хотите указать собственную Нажмите ОК и в появившемся окне выберите иконку, если нет то нажмите ОК и в открывшемся окне выберите Отмена",
        "enter_program_name": "Введите желаемое название исполняемого файла,\nБЕЗ расширения файла!",
        "enter_log_name": "Введите название лог файла для установщика\nМожете ввести полный путь для данного лог файла\nили ничего не вводить если хотите отключить логирование",
        "sau_critical_error": f"Во время установки произошла неизвестная ошибка",
        #GUI
        "custom": "Пользовательская",
        "parameter": "параметра",
        "type": "Тип",
        "date": "Дата",
        "creation": "создания",
        "changes": "Изменения",
        "discoveries": "Открытия",
        "system": "Системная",
        "bit": "Битность",
        "registry": "Реестр",
        "scheduler": "Планировщик",
        "state": "Состояние",
        "unknown": "неизвестно",
        "no": "Нет",
        "change": "Изменить",
        "turn_off": "Отключить",
        "turn_on": "Включить",
        "no_data": "Н/Д",
        "yes": "Да",
        "all_process": "Все Процессы",
        "process2": "Процесса",
        "critical": "Критичность",
        "status": "Статус",
        "user2": "Пользователь",
        "frozen": "Заморожен",
        "critical_process": "Критичные Процессы",
        "suspend_process": "Замороженные Процессы",
        "things": "шт",
        "admin": "Администратор",
        "started": "Запущен",
        "guest": "Гость",
    },
    "en": {
        "RLP": "Load Protection",
        "ARM": "Startup Wizard",
        "AX": "AntiBullshit",
        "PM": "Process Manager",
        "FM": "File Manager",
        "UA": "Unlock All",
        "FE": "File Editor",
        "FR": "Replace Rarely Used Files",
        "CM": "Main Menu",
        "SP": "Virus Scarecrow",
        "CC": "Cache Cleaner",
        "Console": "Developer Console",
        "UM": "User Manager",
        "R": "Restart PC",
        "Run": "Run as Administrator",
        "OBPC": "Voice Control",
        "CC22": 'Caesar Cipher Encryption',
        "EC": "Change Process Criticality",
        "GFA": "Get Full Privileges",
        "OF": "Other Components",
        "RS": "Header Generator",
        "E": "Exit Program",
        "AP": "About Program",
        "SAU": "Settings",
        #AP
        "version_component": "Component Versions",
        "pac": "Gearbox Key",
        "general_component": "Main Components",
        "program_kernel": "Program Kernel (Tray)",
        "mini_component": "Mini Components",
        "system_component": "System Components",
        "support_text": "You can support us by following the link and paying for 2 cans of condensed milk:",
        "steam_trade_text": "or support via Steam Trade",
        "donation_alerts_text": "Support us via DonationAlerts or Steam",
        "license": "License",
        "website_neo_organization": "NEO Organization Website",
        "about_program_text": f"Antivirus A crowbar!\nIt will pull any nail out of your PC's coffin!\n(It will at least try, and if it can't, install Linux)\nCreated by NEO Organization\nPowered by Department K\nCoded by @AnonimNEO, Total lines of code: {all_line}\nProgrammers/Imaginers/Artists/Testers: @AnonimNEO\nLicense: GPL v3.0 Copyleft 🄯 {years_copyleft}\n",
        "ap_exception_text": "An unknown error occurred in the AboutProgram component!",
        "not_stable": "Unavailable due to instability",
        "read_dir_error": "Error reading directory",
        "read_image_error": "Failed to load image",
        #T
        "import_error": "Import error",
        "replacement_is_used": "Replacement is in use",
        "component_import_error": "Error importing Component",
        "component": "Component",
        "not_available": "Not available",
        "not_available2": "Not available",
        "library": "Library",
        "critical_fail_detect": "Critical program corruption detected! The program core cannot be started",
        "damage": "Damage",
        "run_in_recovery": "Running in the Windows recovery environment",
        "run_in_normal": "Running in the standard Windows environment",
        "environment_error": "Error detecting environment",
        "load_bush": "Loading registry hives from disk",
        "unload_bush": "Shutting down, unloading registry hives...",
        "runtime_error": "Critical error initializing program",
        "use_default_font": "Using default font",
        "trey_error": "Tray error",
        "open_with": "Open with",
        "bad_password_for_console": "Invalid captcha entry.\nThe developer console will not launch.",
        "enter_number": "Enter a number",
        "open": "Open",
        "utilities": "Utilities",
        "icon_start_error": "Error starting icon",
        "t_critical_error": "An unknown error occurred in the Tray component",
        "multiprocessing_error": "Critical error while multithreading",
        "restart_program": "Restart the program",
        "admin_error": "Error obtaining administrator privileges",
        #ARM
        "scheduler_error": "Failed to connect to the task scheduler",
        "edit_task_error": "Error changing task state",
        "delete_task_error": "Error deleting tasks",
        "user_not_found": "User not found",
        "enter_user_name": "Enter a valid username",
        "metadata_error": "Error retrieving file metadata",
        "startup_error": "Error accessing user startup folder",
        "key_not_found": "Registry key not found",
        "read_key_error": "Error reading registry key",
        "create_key": "Registry key created",
        "with_type": "with type",
        "in": "in",
        "permission_error": "Insufficient permissions",
        "create_key_error": "Error creating registry key",
        "update_key": "Registry key successfully modified",
        "update_key_error": "Error modifying registry key",
        "delete_key": "Registry key deleted",
        "delete_key_error": "Registry key deleted",
        "file_delete": "File deleted",
        "file_delete_error": "Error deleting file",
        "save_xml_task_error": "Error saving XML task",
        "task_error": "Error processing task",
        "task_dir_error": "Task directory not found",
        "xml_task_error": "Error processing task file",
        "on": "enabled",
        "off": "disabled",
        "task": "Task",
        "success": "successful",
        "from_com": "via COM",
        "from_xml": "via XML",
        "xml_error": "XML error",
        "delete_task_com": "deleted via COM",
        "xml_task_delete": "Task XML file deleted",
        "xml_task_delete_error": "Error deleting XML file",
        "delete_file?": "Are you sure you want to delete the registry value",
        "enter_new_name_key": "Enter the name of the new registry value",
        "for": "for",
        "arm_help_text": 'The Scheduler tab displays so many tasks because viruses could modify tasks, but this is extremely rare, so you can disable the display of tasks without the "created" column. To do this, Click the item in the top panel of the window: view->Show only tasks with date.',
        "arm_critical_error": f"An unknown error occurred in the AutoRunMaster component!",
        "danger": "Угроза",
        "suspend_process_for_name": "Заморозить процессы с именем",
        "kill_process_for_name": "Убить процессы с именем",
        "action_error": "ошибка при действии",
        "": "",
        #Console
        "crowbar_console": "Crowbar Antivirus Developer Console",
        "crowbar_console_text": "Be careful, this component may be unstable.\nAnd not understanding what you're doing can damage the program.\nIf this happens, restart the program.\n",
        "attempt_command": "attempt to execute command",
        "exit_with_console_text": "No, no, I won't let you bypass the captcha (at least I'll try)",
        #EC
        "open_process_error": "Failed to open process",
        "error_code": "Error code",
        "installed": "installed",
        "removed": "removed",
        "process_critical": "Process criticality",
        "target": "target",
        "edit_critical_error": "Error changing criticality",
        "edit_critical_unknown_error": "Unknown error changing criticality",
        "process": "Process",
        "not_found": "not found",
        "criticality_status": "Process criticality value",
        "changed_to": "changed to",
        "no_changed": "not changed",
        "ec_critical_error": "An unknown error occurred in the EditCriticality component",
        #OF
        "pac_text": f"The Program Authentication Key (PAK) is a key for confirming that this program is genuine. If you see the key you specified during compilation, then you are looking at the genuine Antivirus Mount. If the key does not match yours, then you are looking at a clone of the program masquerading as Antivirus Mount. PAK - {program_authentication_clyth}",
        "start_thread": "Successfully started thread for",
        "start_process": "Successfully started process for",
        "start_theard_error": "Error starting thread for process",
        "start_process_error": "Error starting process for process",
        "restart_ca": "Restarting program",
        "system_found": "System found on",
        "unknown_error": "Unknown error",
        "bush_not_found": "Hive file not found",
        "bush": "Hive",
        "success_load": "successfully loaded from",
        "load_bush_error": "Error loading hive",
        "success_unload": "successfully unloaded",
        "unload_bush_error": "Error unloading hive",
        "get_user_name_error": "Error getting user name",
        "open_file_error": "Not found" "unable to open file",
        "with_program": "using the specified program",
        "start_error": "Error starting",
        "start_command_error": "Error executing command",
        #E
        "dyrachok_test_log_text": "Durachok test failed",
        "dyrachok_test_text": "You are watching TikTok!\nThe program will not close.",
        "watch_tiktok?": "Are you watching TikTok?",
        "exit_error": "Error exiting",
        "exit_program": "Exiting program...",
        "bad_capcha": "Incorrect captcha input.\nThe program will not close.",
        "enter_result_example": "Enter the result of this example",
        "bad_result_example": "The example input is incorrect",
        "bad_enter_number": "Incorrect number input",
        "want_exit?": "You Are you sure you want to exit this software?",
        "attempting_to_exit": "Attempting to exit the program",
        "cancel_exit": "Canceled exit",
        "e_critical_error": "An unknown error occurred in the Exit component!",
        #GFA
        "not_dir": "Path does not exist",
        "full_access_set": "Full access set",
        "error": "Error",
        "file_error": "Error while working with file",
        "to_access": "to access",
        "get_sid_error": "Error getting user SID",
        "get_description_error": "Error getting security descriptor",
        "ace_error": "Error adding ACE",
        "set_access_error": "Error setting access rights",
        "success_set_full_access": "Full access to registry set",
        "regedit_error": "Error while working with registry",
        #R
        "attempt_to_reboot": "Attempt to reboot after",
        "r_critical_error": "An unknown error occurred in the method of the Restart Component",
        "next_method": "Proceeding to the next method",
        "all_method_used": "All possible methods of restarting Windows have been tried, none were successful.",
        #SP
        "simulation": "Simulation",
        "removal": "Removal",
        "create_dir": "Directory created",
        "create_dir_error": "Error creating directory",
        "create_file": "File created",
        "create_file_error": "Error creating file",
        "delete_dir": "Directory deleted",
        "delete_dir_error": "Error deleting directory",
        "start_simulation": "Starting simulation for",
        "simulation_for": "Simulation for",
        "completed": "completed",
        "simulation_completed": "Simulation completed.",
        "sp_confirmation": "Are you sure you want to delete all phantom elements?\nThis may damage the actual installed ones.",
        "delete_simulation": "Deleting simulation for",
        "delete_simulation_for": "Deleting simulation for",
        "delete_completed": "Deletion complete.",
        "sp_critical_error": f"An unknown error occurred in the ScarecrowProtection component!",
        #UA
        "start_recovery_font": "Starting font recovery",
        "font_dir_not_found": "Font directory not found",
        "font": "Font",
        "restored": "restored",
        "correct_font": "already correctly written to the registry",
        "add_in_registry": "added to the registry",
        "font_error": "Error processing font",
        "delete_orphan_font": "Orphan font parameter removed",
        "delete_orphan_font_error": "Error deleting orphan parameter",
        "recovery_font_complete": "Font recovery complete. Found",
        "removed_orphans": "orphans removed",
        "recovery_font_error": "Error recovering fonts",
        "parameter": "Parameter",
        "successfully_reset_to": "successfully reset to",
        "unsupported_type_for": "Unsupported type for",
        "not_found_pass": "not found, skip",
        "reset_error": "Error resetting",
        "block_detect": "Blocks detected in",
        "delete_block": "Blocks removed",
        "component_work_complete": "Component work completed",
        "ua_critical_error": "In Component UnlockAll: An unknown error occurred:",
        "au_result": "The Unlock All component has completed its results",
        "unlock": "Unlocked✅",
        "unlock_error": "Unlock error❌",
        "blocks": "Blocks",
        "mouse": "mouse",
        "explorer": "Explorer",
        "user": "user",
        "systems": "systems",
        "fonts": "fonts",
        "check_fonts": "Checking font integrity",
        "all_fonts=": "All font parameters have the same value",
        "not_ttf_or_otf": "Parameter values ​​do not contain .ttf or .otf files",
        "font_problem_detect": "Problems with fonts detected, starting repair",
        "restore_fonts_check_success": "Font integrity check completed successfully, no repair required",
        "check_fonts_error": "Unknown error while checking fonts",
        #UM
        "net_error": "The net command failed",
        "system_command_error": "System error while executing command",
        "user_name": "User name",
        "create_user": "Create user",
        "delete_users": "Delete selected",
        "change_password": "Change password",
        "get_user_list_error": "Error loading user list",
        "password": "Password",
        "enter_all_data": "Fill in all fields.",
        "success_create": "successfully created",
        "create_user_error": "Error creating user",
        "select_user": "Select user.",
        "cant_delete_self": "Cannot delete yourself",
        "what_did_you": "Whatever you wanted",
        "deleted": "deleted",
        "delete_user_error": "Error deleting user",
        "enter_new_password": "Enter new password:",
        "not_empty": "Cannot be empty.",
        "reset": "Reset",
        "reset2": "reset",
        "password_for_user": "Password for user",
        "change_password_error": "Error resetting password for",
        "um_critical_error": "An unknown error occurred in the UsersManager component!",
        #CC
        "start_clean": "Starting Cleanup",
        "from": "from",
        "delete_files_error": "Error deleting the following files",
        "delete_files_success": "Successfully deleted files",
        "cc_log_dir": "The log file was created at the path",
        "cc_critical_error": "An unknown error occurred in the ClearCache component!",
        #CM
        "components": "Components",
        "protect": "Protection",
        "control": "Control",
        "cm_critical_error": "An unknown error occurred in the CrowbarMenu component!",
        #Theme
        "dark": "Dark",
        "white": "Light",
        "red": "Red",
        "blue": "Blue",
        "green": "Green",
        "contrast": "Contrast",
        "gray": "Gray",
        "orange": "Orange",
        "themes": "Themes",
        "topmost": "On top of all windows",
        "on2": "On",
        "off2": "Off",
        "help": "Help",
        "view": "View",
        "show_date": "Show only tasks with a date",
        #FE
        "file": "File",
        "save": "Save",
        "save_as": "Save as",
        "exit": "Exit",
        "editing": "Editing",
        "cancel": "Cancel",
        "repeat": "Repeat",
        "cut": "Cut",
        "copy": "Copy",
        "paste": "Paste",
        "select_all": "Select all",
        "font_size": "Font size",
        "new_file": "New file",
        "text_file": "Text files",
        "all_files": "All files",
        "file_not_found": "File not found",
        "success_saved": "Successfully saved",
        "save_changes?": "You have unsaved changes. Save file before exiting?",
        "match_case": "Match case",
        "whole_words": "Whole Words",
        "back": "Back",
        "next": "Next",
        "fe_critical_error": "An unknown error occurred in the FileEditor component!",
        "cuttlefish": "Sepia",
        #FR
        "created": "Created",
        "replaced": "replaced",
        "on_disc": "on disk",
        "replace_file_not_found": "Failed to replace file",
        "select_file": "First select or specify a file path!",
        "backup": "Backup",
        "on_dir": "on path",
        "restore": "Restore",
        "from_backup": "from backup",
        "restore_from_backup": "Restored from backup",
        "when_restoring_a_file": "when file recovery",
        "your_way": "Your way",
        "sticky_keys": "Sticky keys",
        "specialist_possibilities": "Specialist capabilities",
        "task_manager": "Task Manager",
        "explorer": "Explorer",
        "what_to_replace": "What to replace with",
        "review": "Review",
        "what_are_replace": "What to replace",
        "select_preset": "Select a preset...",
        "replace": "Replace",
        #FM
        "skip_file": "Skipped file",
        "copy_path": "Copy path",
        "search": "Search",
        "loading": "Loading",
        "enter_path": "Enter path",
        "available_disks": "Available disks",
        "path": "Path",
        "delete": "Delete",
        "elements": "elements",
        "you_want_to_delete": "Are you sure you want to delete",
        "delete_error": "Error deleting",
        "elements_copy": "Items copied",
        "clipboard_is_empty": "Clipboard is empty",
        "paste_error": "Paste error",
        "access_check_error_for": "Access check error for",
        "properties": "Properties",
        "meaning": "Value",
        "name": "Name",
        "location": "Location",
        "size": "Size",
        "changed": "Changed",
        "opened": "Opened",
        "file_version": "File version",
        "author": "Author",
        "access_for": "Access permissions for",
        "full_access": "Full access",
        "reading": "Read",
        "record": "Write",
        "launch": "Launching",
        "collecting_properties_error": "Error collecting properties for",
        "read_file_properties_error": "Failed to read file properties",
        "invalid_characters": "contains invalid characters characters",
        "current": "Current",
        "dir": "Directory",
        "new_name_for": "New name for",
        "already_exists": "already exists",
        "name_file_or_dir": "File or directory with the name",
        "renamed": "Renamed",
        "when_renaming": "When renaming",
        "enter_data_file": "Enter content for the file",
        "restore_focus_error": "Failed to restore focus to",
        "up": "Up",
        "rename": "Rename",
        "get_full_access": "Get full access",
        "edit_file": "Edit file",
        "create": "Create",
        "update": "Update",
        "not_dir_selected": "No directory selected for insertion",
        "source_file_not_found": "Source not found (may have been moved)",
        "dont_copy_in_in": "Cannot copy or move item to the same directory",
        "replace_it": "Replace it?",
        "copied2": "Copied",
        "fm_help_text": "Welcome to File Manager!\nThis component supports:\n1) Full keyboard control\n2) Search - to access it, click the item in the upper left part of the window.",
        "text_for_search": "Search text:",
        "in_current_dir": "In the current directory",
        "cancel2": "Cancel",
        "enter_text_for_search": "Enter search text:",
        "not_current_tab_for_search": "No active tab for searching.",
        "files_containing": "Files containing",
        "not_founded": "not found",
        "info_dir_error": "Error getting directory information",
        "info_file_error": "Error getting file information",
        "search_result": "Search results",
        "fm_exit": "Are you sure you want to exit?",
        "fm_critical_error": "An unknown error occurred in FileManager!",
        #PM
        "info_process_error": "Error getting process information",
        "ok": "OK",
        "at": "at",
        "kill_processes": "Kill processes",
        "suspend": "Freeze",
        "resume": "Unfreeze",
        "make_it_critical": "Make critical",
        "remove_criticality": "Remove criticality",
        "to_file": "to file",
        "pm_help_text": "Welcome to Process Manager! It supports: 1) Selecting and working with multiple processes 2) Search - to open it, click the item in the upper left part of the window. 3) Frozen processes are marked in gray, and critical ones are marked in red. There are also tabs for easy navigation. Please note that Windows creates its own four critical svhost.exe processes, but a virus can change these values, so be careful!",
        "cancel_search": "Stop search",
        "actions": "Actions",
        "pm_critical_error": "An unknown error occurred in the ProcessManager component!",
        #Run
        "standard": "Accessories",
        "regedit": "Registry Editor",
        "taskmgr": "Task Manager",
        "notepad": "Notepad",
        "explorer": "File Explorer",
        "cmd": "Command Prompt",
        "powershell": "PowerShell",
        "commands": "Commands",
        "cancel_reboot": "Cancel reboot/shutdown",
        "reboot_pc": "Reboot PC",
        "shutdown_pc": "Shutdown PC",
        "end_session": "End session",
        "mode": "Mode:",
        "professional": "professional",
        "simplified": "simplified",
        "file2": "file",
        #SAU
        "compilations": "Compilations",
        "command_end_with_code": "Command ended with code",
        "t_compilation_is_finish": "Trey Component compilation completed!",
        "setting_saved_in": "Settings successfully saved to",
        "settings_save_error": "Error saving settings",
        "settings_backup_created_ob_path": "Settings backup created at path",
        "settings_export_success": "Export successful, saved to",
        "settings_backup_created_error": "Error creating backup",
        "settings_export_error": "Error exporting settings",
        "archive": "Archive",
        "not_compilation": "Recompilation not possible",
        "bad_archive": "Invalid archive format or corrupted archive",
        "success_unpacked": "successfully unpacked",
        "unpacked_archive_error": "Error unpacking archive",
        "moved": "moved",
        "content": "Contents",
        "moved_error": "Error moving files",
        "enter_path_to_image": "Enter the directory where to move the images. Do not enter anything if the images are already in the desired directory (for example, you are simply updating the program)",
        "for_copy_image": "images to the directory",
        "for_copy": "for copying",
        "copy_error": "Error When copying",
        "copy_file_error": "images\nYou may have entered incorrect data. You can move the files yourself. They are located in the program directory.",
        "enter_exe_name": "Enter the directory where to move the executable file\nalong with the file name, including the .exe extension!",
        "copy_exe_error": "You may have entered incorrect data. You can move the files yourself. They are located in the program directory.",
        "create_lnk_success": "Shortcut successfully created on the desktop",
        "create_lnk_error": "Errors creating shortcut",
        "successfully_changed_to": "successfully changed to",
        "add_to_autorun_error": "Error adding program to startup",
        "add_program_to_autorun": "Add program to startup?",
        "add_program_to_autorun_error": "An error occurred while adding the program to startup.",
        "path_must_string": "Path must be a string.",
        "number_must_be_1_to": "Number must be between 1 and.",
        "enter_number": "Enter a number.",
        "enter_string": "Value must be a string.",
        "field_cannot_be_empty": "Field cannot be empty.",
        "use": "Use.",
        "must_list": "Must be a list, tuple, set, or dictionary.",
        "syntaxis_error": "Syntax error.",
        "invalid_format": "Invalid format.",
        "must_be_dictionary": "Value must be a dictionary.",
        "dictionary_must_contain_key": "Dictionary must contain key.",
        "read_comments_error": "Error reading comments from.",
        "parsing_error": "Parsing error.",
        "fix_problems_in_fields": "Fix errors in fields (marked in red)",
        "recompilation_required_continue": "Recompilation required!\nContinue?",
        "create_backup": "Creating a backup...",
        "create_backup_error": "Error creating backup",
        "save_settings": "Saving settings...",
        "save_settings_error": "Error saving settings",
        "unpacking_source_code": "Unpacking source...",
        "unpacking_source_code_error": "Error unpacking source code",
        "preparing_files": "Preparing files...",
        "preparing_files": "Preparing files...",
        "compilation": "Compiling",
        "during_recompilation": "during recompilation",
        "copying_files": "Copying files...",
        "adding_to_autorun": "Adding to startup...",
        "completed": "completed",
        "delete_compiling_cache": "Are you sure you want to delete all cache and Temporary .py files?",
        "clean_completed_deleted_objects": "Cleaning completed.\nDeleted objects",
        "clean_cache_error": "Error clearing cache",
        "ready": "Ready to use",
        "open_error": "Failed to open",
        "log": "File log",
        "export": "Export",
        "import": "Import",
        "delete_cache": "Delete Cache",
        "apply": "Apply",
        "sau_start_text": "Please note that changing parameters is impossible without recompiling the program!\n\nWe recommend exporting the settings (thereby creating a backup copy of the settings) before making changes.\n\nDo you want to continue?",
        "icon_not_found": "The program icon was not found. If you want to specify your own, click OK and select an icon in the window that appears. Otherwise, click OK and select Cancel in the window that appears.",
        "enter_program_name": "Enter the desired executable file name, \nWITHOUT the file extension!",
        "enter_log_name": "Enter the name of the log file for the installer. \nYou can enter the full path to this log file, \nor leave it blank if you want to disable logging.",
        "sau_critical_error": f"An unknown error occurred during installation.",
        #GUI
        "custom": "Custom",
        "parameter": "parameter",
        "type": "Type",
        "date": "Date",
        "creation": "Creation",
        "changes": "Changes",
        "discoveries": "Discoveries",
        "system": "System",
        "bit": "Bit depth",
        "registry": "Registry",
        "scheduler": "Scheduler",
        "state": "State",
        "unknown": "unknown",
        "no": "No",
        "change": "Change",
        "turn_off": "Disable",
        "turn_on": "Enable",
        "no_data": "N/A",
        "yes": "Yes",
        "all_process": "All Processes",
        "process2": "Process",
        "critical": "Criticality",
        "status": "Status",
        "user2": "User",
        "frozen": "Frozen",
        "critical_process": "Critical Processes",
        "suspend_process": "Frozen Processes",
        "things": "items",
        "admin": "Administrator",
        "started": "Started",
        "guest": "Guest",
    },
}
